export const ADVANCE_PHASE = 'ADVANCE_PHASE';
export const START_LESSON = 'START_LESSON';
export const ADD_CHAR = 'ADD_CHAR';


export const FETCH_HANLIST_START = 'FETCH_HANLIST_START';
export const FETCH_HANLIST_SUCCESS = 'FETCH_HANLIST_SUCCESS';
export const FETCH_HANLIST_FAILED = 'FETCH_HANLIST_FAILED';

